config/routes.rb
Rideboard::Application.routes.draw do
  resources :requests

  get "info/about"

  resources :rides

  get "home/index"
  
  root :to => "rides#index"

end

app/models/request.rb
class Request < ActiveRecord::Base
  attr_accessible :address, :comments, :date_range_end, :date_range_start, :email, :first_name, :last_name, :phone_number

   # validations
  validates_presence_of :date_range_end, :date_range_start, :email, :first_name, :last_name, :address 

  acts_as_gmappable


  def gmaps4rails_address
    address
  end

  def gmaps4rails_infowindow
      # add here whatever html content you desire, it will be displayed when users clicks on the marker
    "Name: #{self.first_name} #{self.last_name}
     <br />
     Leaving between: #{self.date_range_start.to_formatted_s(:long_ordinal)} and #{self.date_range_start.to_formatted_s(:long_ordinal)}
     <br />
     Phone number: #{self.phone_number}
     <br />
     Email: #{self.email}
     <br />
     Additional comments: #{self.comments}"     
  end

end

app/models/ride.rb
require 'bcrypt'

class Ride < ActiveRecord::Base
  attr_accessible :comments, :date_range_end, :date_range_start, :email, :first_name, :last_name, :phash, :phone_number, :request, :address


  # validations
  validates_presence_of :date_range_end, :date_range_start, :email, :first_name, :last_name, :address 

  acts_as_gmappable


  def gmaps4rails_address
    address
  end

  def gmaps4rails_infowindow
      # add here whatever html content you desire, it will be displayed when users clicks on the marker
    "Name: #{self.first_name} #{self.last_name}
     <br />
     Leaving between: #{self.date_range_start.to_formatted_s(:long_ordinal)} and #{self.date_range_start.to_formatted_s(:long_ordinal)}
     <br />
     Phone number: #{self.phone_number}
     <br />
     Email: #{self.email}
     <br />
     Additional comments: #{self.comments}"     
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def about
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
# @json = Request.all.to_gmaps4rails
    @json = Request.where('date_range_end >= ?', Date.today).all.to_gmaps4rails

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @requests }
    end
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
    @request = Request.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @request }
    end
  end

  # GET /requests/new
  # GET /requests/new.json
  def new
    @request = Request.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @request }
    end
  end

  # GET /requests/1/edit
#  def edit
#   @request = Request.find(params[:id])
#  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(params[:request])

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render json: @request, status: :created, location: @request }
      else
        format.html { render action: "new" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /requests/1
  # PUT /requests/1.json
  def update
    @request = Request.find(params[:id])

    respond_to do |format|
      if @request.update_attributes(params[:request])
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
# def destroy
#    @request = Request.find(params[:id])
#   @request.destroy
#
#   respond_to do |format|
#     format.html { redirect_to requests_url }
#     format.json { head :no_content }
#   end
# end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  # GET /rides
  # GET /rides.json
  def index
    @rides = Ride.all
#    @json = Ride.all.to_gmaps4rails
    @json = Ride.where('date_range_end >= ?', Date.today).all.to_gmaps4rails

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rides }
    end
  end

  

  # GET /rides/1
  # GET /rides/1.json
  def show
    @ride = Ride.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ride }
    end
  end

  # GET /rides/new
  # GET /rides/new.json
  def new
    @ride = Ride.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ride }
    end
  end

  # GET /rides/1/edit
#  def edit
#   @ride = Ride.find(params[:id])
#  end

  # POST /rides
  # POST /rides.json
  def create
    @ride = Ride.new(params[:ride])

    respond_to do |format|
      if @ride.save
        format.html { redirect_to @ride, notice: 'Ride was successfully created.' }
        format.json { render json: @ride, status: :created, location: @ride }
      else
        format.html { render action: "new" }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rides/1
  # PUT /rides/1.json
  def update
    @ride = Ride.find(params[:id])

    respond_to do |format|
      if @ride.update_attributes(params[:ride])
        format.html { redirect_to @ride, notice: 'Ride was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rides/1
  # DELETE /rides/1.json
#  def destroy
#   @ride = Ride.find(params[:id])
#   @ride.destroy

#   respond_to do |format|
#     format.html { redirect_to rides_url }
#     format.json { head :no_content }
#   end
#  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/info/about.html.erb
<h1>About</h1>
<br />
<p>About</p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "OC Rideboard", root_path, :class => 'brand' %>
<ul class="nav">
      <li><%= link_to "Rides Offered", "/rides" %></li>
      <li><%= link_to "Rides Requested", "/requests"%></li>
      <li><%= link_to "Offer a Ride", new_ride_path %></li> 
      <li><%= link_to "Add a Request", new_request_path %></li>
      <li><%= link_to "About OC Rideboard", info_about_path%></li>  
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "OC Rideboard" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= stylesheet_link_tag 'gmaps4rails' %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
    <%= yield :scripts %>
  </body>
</html>

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :date_range_start %>
    <%= f.date_select :date_range_start %>
  </div>
  <div class="field">
    <%= f.label :date_range_end %>
    <%= f.date_select :date_range_end %>
  </div>
  <div class="field">
    <%= f.label :comments %>
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<h1>Listing requests</h1>
<br />
<%= gmaps4rails(@json) %>

app/views/requests/new.html.erb
<h1>New request</h1>
<br />
<%= render 'form' %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @request.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @request.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @request.email %>
</p>

<p>
  <b>Phone number:</b>
  <%= @request.phone_number %>
</p>

<p>
  <b>Date range start:</b>
  <%= @request.date_range_start %>
</p>

<p>
  <b>Date range end:</b>
  <%= @request.date_range_end %>
</p>

<p>
  <b>Comments:</b>
  <%= @request.comments %>
</p>

<p>
  <b>Address:</b>
  <%= @request.address %>
</p>


<%= link_to 'Back', requests_path %>

app/views/rides/_form.html.erb
<%= form_for(@ride) do |f| %>
  <% if @ride.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ride.errors.count, "error") %> prohibited this ride from being saved:</h2>

      <ul>
      <% @ride.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br />
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :leaving_between %>
    <%= f.date_select :date_range_start %>
  </div>
  <div class="field">
    <%= f.label :and %>
    <%= f.date_select :date_range_end %>
  </div>
  <div class="field">
    <%= f.label :comments %>
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rides/edit.html.erb
<h1>Editing ride</h1>

<%= render 'form' %>

<%= link_to 'Show', @ride %> |
<%= link_to 'Back', rides_path %>

app/views/rides/index.html.erb
<h1>Rides Offered</h1>
<br />
<%= gmaps4rails(@json) %>

app/views/rides/new.html.erb
<h1>New ride</h1>

<%= render 'form' %>

<%= link_to 'Back', rides_path %>

app/views/rides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @ride.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @ride.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @ride.email %>
</p>

<p>
  <b>Phone number:</b>
  <%= @ride.phone_number %>
</p>


<p>
  <b>Date range start:</b>
  <%= @ride.date_range_start %>
</p>

<p>
  <b>Date range end:</b>
  <%= @ride.date_range_end %>
</p>

<p>
  <b>Comments:</b>
  <%= @ride.comments %>
</p>


<%= link_to 'Back', rides_path %>